
# Copyright (c) 2015-2020 Agalmic Ventures LLC (www.agalmicventures.com)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#Cache the virtual environment
cache:
  paths:
    - env/

#Ensure the virtual environment is installed
before_script:
  - python3 -m venv env
  - source env/bin/activate
  - pip3 install -r requirements.txt

stages:
  - lint
  - test
  - documentation

shellcheck_lint_job:
  stage: lint
  script:
    - shellcheck *.sh
  only:
    - master

help_test_job:
  stage: test
  script:
    - NanoPcap/Tools/Dump.py -h
    - NanoPcap/Tools/Filter.py -h
    - NanoPcap/Tools/Merge.py -h
    - NanoPcap/Tools/Split.py -h
    - NanoPcap/Tools/SplitFlows.py -h
    - NanoPcap/Tools/Summary.py -h
  only:
    - master

smoke_test_job:
  stage: test
  script:
    #Dump
    #Short
    - NanoPcap/Tools/Dump.py TestData/EmptyNs.pcap
    - NanoPcap/Tools/Dump.py TestData/SSH_L3.pcap
    - NanoPcap/Tools/Dump.py TestData/SSH2_L3.pcap
    - NanoPcap/Tools/Dump.py -j TestData/Empty.pcap.gz #Gzipped
    #Long
    - NanoPcap/Tools/Dump.py -l TestData/EmptyNs.pcap
    #JSON
    - NanoPcap/Tools/Dump.py -j TestData/EmptyNs.pcap
    - NanoPcap/Tools/Dump.py -j TestData/SSH_L3.pcap
    - NanoPcap/Tools/Dump.py -j TestData/SSH2_L3.pcap

    #Filter
    #Pass through
    - NanoPcap/Tools/Filter.py TestData/EmptyNs.pcap /dev/null
    - NanoPcap/Tools/Filter.py TestData/SSH_L3.pcap TestData/SSH_L3_Copy.pcap
    - diff TestData/SSH_L3.pcap TestData/SSH_L3_Copy.pcap
    - NanoPcap/Tools/Filter.py TestData/SSH2_L3.pcap /dev/null
    #Randomized drops
    - NanoPcap/Tools/Filter.py -D 0.75 TestData/SSH_L3.pcap /dev/null
    - NanoPcap/Tools/Filter.py -D 0.25 TestData/SSH2_L3.pcap /dev/null
    #Randomized duplicates
    - NanoPcap/Tools/Filter.py --duplicate-fraction 0.5 TestData/SSH_L3.pcap /dev/null
    - NanoPcap/Tools/Filter.py --duplicate-fraction 1.0 TestData/SSH_L3.pcap TestData/SSH_L3_Duplicate.pcap
    #Round trip through gzip
    - NanoPcap/Tools/Filter.py TestData/SSH_L3.pcap TestData/SSH_L3.pcap.gz
    - NanoPcap/Tools/Filter.py TestData/SSH_L3.pcap.gz TestData/SSH_L3_Gzip.pcap
    - diff TestData/SSH_L3.pcap TestData/SSH_L3_Gzip.pcap

    #Merge
    #File + empty = file
    - NanoPcap/Tools/Merge.py TestData/SSH_L3.pcap TestData/Empty.pcap TestData/SSH_L3_MergeCopy.pcap
    - diff TestData/SSH_L3.pcap TestData/SSH_L3_MergeCopy.pcap
    #File + file = duplicated file
    - NanoPcap/Tools/Merge.py TestData/SSH_L3.pcap TestData/SSH_L3.pcap TestData/SSH_L3_DuplicateMerge.pcap
    #TODO: - diff TestData/SSH_L3_Duplicate.pcap TestData/SSH_L3_DuplicateMerge.NanoPcap
    #Deduplicated duplicated file = file
    - NanoPcap/Tools/Filter.py --deduplication-window 5 TestData/SSH_L3_DuplicateMerge.pcap TestData/SSH_L3_DuplicateMerge_Deduplicated.pcap
    - diff TestData/SSH_L3.pcap TestData/SSH_L3_DuplicateMerge_Deduplicated.pcap
    #More advanced merge
    - NanoPcap/Tools/Merge.py TestData/SSH_L3.pcap TestData/SSH2_L3.pcap /dev/null

    #Split
    #TODO

    #Split flows
    #TODO

    #Summary
    #Without units
    - NanoPcap/Tools/Summary.py TestData/EmptyNs.pcap
    - NanoPcap/Tools/Summary.py TestData/SSH_L3.pcap
    - NanoPcap/Tools/Summary.py TestData/SSH2_L3.pcap
    #With units
    - NanoPcap/Tools/Summary.py -u TestData/EmptyNs.pcap
    - NanoPcap/Tools/Summary.py -u TestData/SSH_L3.pcap
    - NanoPcap/Tools/Summary.py -u TestData/SSH2_L3.pcap
  only:
    - master

unit_test_job:
  stage: test
  script:
    - python3 -m unittest discover
  only:
    - master

documentation_job:
  stage: documentation
  artifacts:
    expire_in: 30d
    paths:
      - docs/
  script:
    - ./GenerateDocs.sh
  only:
    - master
