
before_script:
  - python3 -m venv myenv
  - source myenv/bin/activate
  - pip3 install -r requirements.txt

after_script:
  - deactivate

stages:
  - test

smoke_test_job:
  stage: test
  script:
    - NanoPcap/Tools/PcapDump.py -h
  only:
    - master

unit_test_job:
  stage: test
  script:
    - python3 -m unittest discover
  only:
    - master

