before_script:
  - python3 -m venv myenv
  - source myenv/bin/activate
  - pip3 install -r requirements.txt

after_script:
  - deactivate

stages:
  - test
  - documentation

help_test_job:
  stage: test
  script:
    - NanoPcap/Tools/Dump.py -h
    - NanoPcap/Tools/Filter.py -h
    - NanoPcap/Tools/Merge.py -h
    - NanoPcap/Tools/Summary.py -h
  only:
    - master

smoke_test_job:
  stage: test
  script:
    #Dump
    #Short
    - NanoPcap/Tools/Dump.py TestData/EmptyNs.pcap
    - NanoPcap/Tools/Dump.py TestData/SSH_L3.pcap
    - NanoPcap/Tools/Dump.py TestData/SSH2_L3.pcap
    - NanoPcap/Tools/Dump.py -j TestData/Empty.pcap.gz #Gzipped
    #Long
    - NanoPcap/Tools/Dump.py -l TestData/EmptyNs.pcap
    #JSON
    - NanoPcap/Tools/Dump.py -j TestData/EmptyNs.pcap
    - NanoPcap/Tools/Dump.py -j TestData/SSH_L3.pcap
    - NanoPcap/Tools/Dump.py -j TestData/SSH2_L3.pcap

    #Filter
    #Pass through
    - NanoPcap/Tools/Filter.py TestData/EmptyNs.pcap /dev/null
    - NanoPcap/Tools/Filter.py TestData/SSH_L3.pcap /dev/null
    - NanoPcap/Tools/Filter.py TestData/SSH2_L3.pcap /dev/null
    #Randomized drops
    - NanoPcap/Tools/Filter.py -D 0.75 TestData/SSH_L3.pcap /dev/null
    - NanoPcap/Tools/Filter.py -D 0.25 TestData/SSH2_L3.pcap /dev/null
    #Randomized duplicates
    - NanoPcap/Tools/Filter.py --duplicate-fraction 0.5 TestData/SSH_L3.pcap /dev/null
    - NanoPcap/Tools/Filter.py --duplicate-fraction 1.0 TestData/SSH_L3.pcap TestData/SSH_L3_Duplicate.pcap

    #Merge
    #File + empty = file
    - NanoPcap/Tools/Merge.py TestData/SSH_L3.pcap TestData/Empty.pcap TestData/SSH_L3_Copy.pcap
    - diff TestData/SSH_L3.pcap TestData/SSH_L3_Copy.pcap
    #File + file = duplicated file
    - NanoPcap/Tools/Merge.py TestData/SSH_L3.pcap TestData/SSH_L3.pcap TestData/SSH_L3_DuplicateMerge.pcap
    - diff TestData/SSH_L3_Duplicate.pcap TestData/SSH_L3_DuplicateMerge.pcap
    #More advanced merge
    - NanoPcap/Tools/Merge.py TestData/SSH_L3.pcap TestData/SSH2_L3.pcap /dev/null

    #Summary
    #Without units
    - NanoPcap/Tools/Summary.py TestData/EmptyNs.pcap
    - NanoPcap/Tools/Summary.py TestData/SSH_L3.pcap
    - NanoPcap/Tools/Summary.py TestData/SSH2_L3.pcap
    #With units
    - NanoPcap/Tools/Summary.py -u TestData/EmptyNs.pcap
    - NanoPcap/Tools/Summary.py -u TestData/SSH_L3.pcap
    - NanoPcap/Tools/Summary.py -u TestData/SSH2_L3.pcap
  only:
    - master

unit_test_job:
  stage: test
  script:
    - python3 -m unittest discover
  only:
    - master

documentation_job:
  stage: documentation
  artifacts:
    expire_in: 30d
    paths:
      - docs/
  script:
    - ./GenerateDocs.sh
  only:
    - master
